### ISSUE TITLE
Zhiyuan migration plan

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-docker-siyuan#127]
Zhiyuan mirror has been running legacy infrastructure for a long time. We plan to migrate it to current infrastructure.

To maintain a minimal downtime and deliver new infrastructure, we propose the following migration plan.

## Preparation phase

- [ ] remove reverse proxy repos https://github.com/sjtug/mirror-requests/issues/143 , either by redirect or by using mirror-intel
- [ ] writing scripts for zhiyuan in this repo
- [ ] change repo name to mirror-docker-unified

## Transition phase

In transition phase, we first start new web server, and then migrate related services.

- [ ] stop old rsync
- [ ] start new rsync
- [ ] start new services except caddy and lug
- [ ] stop old caddy (downtime begin)
- [ ] start new caddy
- [ ] stop old lug
- [ ] start new lug

This completes the migration.

## Result

With this migration, we would have the following new features.

* mirror-intel repos are running on both servers. Users may select any server they want.
* git repos are directly redirected to git.sjtu.edu.cn
* no more public metrics, they are all hidden behind http basic auth

**Comment by CherryRum** [comment]
Use S3 to synchronize maven ?

**Comment by skyzh** [comment]
>  Use S3 to synchronize maven ?

No plan for this.
