### ISSUE TITLE
caddy: properly handle http to https redirect

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-docker-siyuan#17]
For ubuntu, debian and other repos that 1. with GPG key 2. minimal distribution doesn't support https, we could disable http to https redirect. For main page and other sites, enable https redirections.

This issue should be solved without breaking file server. (e.g. `ubuntu -> ubuntu/` and hyperlinks under `ubuntu/`)

**Comment by BugenZhao** [comment]
I'm working on this in #23 .
