### ISSUE TITLE
lug: logging to ELK stack

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-docker-siyuan#25]
In https://github.com/sjtug/mirror-docker-siyuan/pull/24 , we added support for sending docker syslog to ELK stack. LUG also supports logging. As we need to hide real ELK address in environment file, we should find a way to dynamically generate config based on environment file (or add env support for lug).

**Comment by doctormin** [comment]
Will issue this tomorrow

**Comment by skyzh** [comment]
I'll take care of this part.
