### ISSUE TITLE
lug: check mirror consistency

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-docker-siyuan#36]
It seems that some repos have totally different structures from our selected upstreams and ftp.sjtu.edu.cn. Please check if there is any inconsistency of upstream and ftp.sjtu.edu.cn repos. (e.g. Fedora). If so, report it here and we would discuss how to handle it.

**Comment by skyzh** [comment]
* we should sync `fedora` to `fedora/linux`

**Comment by doctormin** [comment]
Got it

**Comment by doctormin** [comment]
## Same as [tuna](https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status):
+ CentOS            
  
    + [sjtu](http://ftp.sjtu.edu.cn/centos/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/centos/)
    
+ debian              
  
     + [sjtu](http://ftp.sjtu.edu.cn/debian/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/debian/)
     
+ debian-cd         
  
     + [sjtu](http://ftp.sjtu.edu.cn/debian-cd/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/debian-cd/)
     
+ debian-security
  
     + [sjtu](http://ftp.sjtu.edu.cn/debian-security/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/debian-security/)
     
+ deepin
  
  + [sjtu](http://ftp.sjtu.edu.cn/deepin/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/deepin/)
  
+ docker-ce
  
     + [sjtu](http://mirrors.internal.skyzh.xyz/docker-ce/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/docker-ce/)
     
+ linuxmint
  
     + [sjtu](http://ftp.sjtu.edu.cn/linuxmint/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/linuxmint/)
     
+ linuxmint-cd
  
     + [sjtu](http://ftp.sjtu.edu.cn/linuxmint-cd/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/linuxmint-cd/)
     
+ mageia
  
  + [sjtu](http://ftp.sjtu.edu.cn/mageia/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/mageia/)
  
+ opensuse
  
  + [sjtu](http://ftp.sjtu.edu.cn/opensuse/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/opensuse/)
  
+ remi

     + [sjtu](http://ftp.sjtu.edu.cn/remi/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/remi/)

+ ubuntu

     + [sjtu](http://ftp.sjtu.edu.cn/ubuntu/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/ubuntu/)

     

## [tuna](https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status) doesn't have:

+ csw
  + [sjtu](http://ftp.sjtu.edu.cn/csw/)
+ deepin-cd
  
  + [sjtu](http://ftp.sjtu.edu.cn/deepin-cd/)
+ fedora-secondary

  + [sjtu](http://ftp.sjtu.edu.cn/fedora-secondary/)
+ openvz

  + [sjtu](http://ftp.sjtu.edu.cn/openvz/)

+ scientific
  + [sjtu](http://ftp.sjtu.edu.cn/scientific/)
+ ubuntu-cd
  + [sjtu](http://ftp.sjtu.edu.cn/ubuntu-cd/)



## different from [tuna](https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status):

+ fedora
  
  + [sjtu](http://ftp.sjtu.edu.cn/fedora/)-[tuna](https://mirrors.tuna.tsinghua.edu.cn/help/fedora/)

**Comment by skyzh** [comment]
Thanks for your work! Then we will only have to resolve the fedora issue.
