### ISSUE TITLE
lug configuration

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-docker-siyuan#4]
I would recommend create two lug configuration. One for bootstrapping our mirror site, by using mirrors.tuna and mirrors.ustc. And another one for production use, where we synchronize files directly from official upstream.

- [x] lug config for bootstrapping
- [x] lug config for production
- [x] validate config with GitHub Action (refer to mirrors-docker repo for current CI config)

Please double check if the configuration contains any sensitive information (e.g. username/password of rsync endpoint). If so, please create issue for them.

**Comment by skyzh** [comment]
Please include all repos in ftp.sjtu in our new mirror site.

**Comment by doctormin** [comment]
working on "config for bootstrapping" now

**Comment by doctormin** [comment]
- [ ] lug config for bootstrapping
- [x ] lug config for production   (almost done)
- [ ] validate config with GitHub Action (refer to mirrors-docker repo for current CI config)

**Comment by skyzh** [comment]
For the remaining two tasks, we now have a different approach.

* We could sync directly from ftp.sjtu.edu.cn. Just set the source to be `rsync://ftp.sjtu.edu.cn/<name>`, and I'll contact the admin to expose them in rsync.
* It seems that we haven't got a mature way to validate lug config. So you could just use tools to verify if it is a validate yaml file.
