### ISSUE TITLE
caddy configuration

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-docker-siyuan#5]
On siyuan mirror server, we will only have `shell_script` type of synchronization jobs. So it's relatively easy to make a `Caddyfile` generator on this new site.

- [ ] `Caddyfile` generator
- [ ] Use GitHub Action to check caddy config (is there any command like `docker-compose run caddy --check`?)

**Comment by skyzh** [comment]
Please double check if the configuration contains any sensitive information (e.g. username/password of rsync endpoint). If so, please create issue for them.

**Comment by skyzh** [comment]
To make things easy, I would suggest:

* for all `shell_script` type of site, just use `fileserver` at root instead of at each separate site. We've met with redirection issues several times, and I personally don't want to get this complex.
* for other types, generate sub site that take precedence of fileserver root site.
* if possible, take two config.yaml and generate redirect to another site.

**Comment by skyzh** [comment]
e.g.
* click on any link in https://mirrors.sjtug.sjtu.edu.cn/archlinux will cause 404
* access mirrors.sjtug.sjtu.edu.cn/archlinux/core will cause wrong redirection
* mirrors.sjtug.sjtu.edu.cn/manjarostable is the same as mirrors.sjtug.sjtu.edu.cn/manjaro/stable , and many users are using the former URL

**Comment by BugenZhao** [comment]
- [x] A basic refactored generator
- [x] Redirect `/ubuntu` to `/ubuntu/` (301)
- [ ] ...
- [ ] Caddyfile validation on CI
