### ISSUE TITLE
lug: fix upstream

### ISSUE THREAD

**Issue by skyzh** [sjtug/mirror-docker-siyuan#53]
CentOS: `Stderr: @ERROR: Unknown module 'CentOS'\nrsync error: error starting client-server protocol (code 5) at main.c(1675) [Receiver=3.1.3]\n`

We need to add our server to official upstream before using official rsync server. So we have to first use a tier-1 upstream (such as tuna, or mirrors.kernel.org, etc)

Debian has no output `siyuan-lug      | time="2020-11-09T03:22:51Z" level=info msg="Stderr: " worker=debian`. Seems that the server requires a password. We have to switch to another upstream.

You may use rsync to check if an upstream can be used. e.g.

```
rsync -avH rsync://syncproxy2.wna.debian.org/debian/ . --dry-run --stats
```

**Comment by doctormin** [comment]
Got it.  Thank you for your instructions :)
